name: Collect BLS Data

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the first day of every month at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-data:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch and Update BLS Data
        run: |
          python scripts/bls_data_collector.py
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add data/labor_stats.csv
          git commit -m "Update labor statistics data"
          git push
